/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_schspa_SysfsInterface */

#ifndef _Included_com_schspa_SysfsInterface
#define _Included_com_schspa_SysfsInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_schspa_SysfsInterface
 * Method:    read
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_schspa_SysfsInterface_read
  (JNIEnv *, jobject, jstring);

JNIEXPORT jstring JNICALL Java_com_schspa_SysfsInterface_write
        (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT jobjectArray JNICALL Java_com_schspa_SysfsInterface_getfile(JNIEnv *,
                                                                      jobject, jstring);
/*
 * Class:     com_schspa_SysfsInterface
 * Method:    read
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_schspa_SysfsInterface_test
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
